### ISSUE TITLE
 audio-record interface not connected

### ISSUE THREAD

**Issue by pixelr0** [popey/vokoscreenng-snap#3]
https://github.com/vkohaupt/vokoscreenNG/issues/89#issuecomment-638628763
https://github.com/vkohaupt/vokoscreenNG/issues/89#issuecomment-644382439
some people are having problems with the snap.

can't confirm, works fine for me on 20.04

**Comment by vkohaupt** [comment]
Please show in the terminal
snap list
and
snap connections

Thanks

**Comment by pixelr0** [comment]
```
~$ snap list vokoscreen-ng 
Name           Version  Rev  Tracking       Publisher  Notes
vokoscreen-ng  3.0.4    75   latest/stable  popey      -

~$ snap connections vokoscreen-ng 
Interface        Plug                           Slot             Notes
audio-playback   vokoscreen-ng:audio-playback   :audio-playback  -
audio-record     vokoscreen-ng:audio-record     -                -
camera           vokoscreen-ng:camera           :camera          -
desktop          vokoscreen-ng:desktop          :desktop         -
desktop-legacy   vokoscreen-ng:desktop-legacy   :desktop-legacy  -
home             vokoscreen-ng:home             :home            -
mount-observe    vokoscreen-ng:mount-observe    :mount-observe   -
network          vokoscreen-ng:network          :network         -
opengl           vokoscreen-ng:opengl           :opengl          -
removable-media  vokoscreen-ng:removable-media  -                -
unity7           vokoscreen-ng:unity7           :unity7          -
x11              vokoscreen-ng:x11              :x11             -
```

**Comment by pixelr0** [comment]
ooof, it records fine but without audio. so yeah, the audio-record stuff in not connected? and i can't enable audio-recording (there is no permission to enable it from snap store -> permissions)

**Comment by pixelr0** [comment]
whaaat? now there is a "Record audio" permission in Ubuntu Software. it is off by default but i can turn it ON. with Record audio ON records fine, both video and audio work. if i turn OFF the "Record audio" permission then i get a 0 bytes file, not even video :/ weird

**Comment by popey** [comment]
This should now be resolved as the audio-record plug is auto connected. https://forum.snapcraft.io/t/audio-record-for-vokoscreen-ng/18443
