### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by vkohaupt** [popey/vokoscreenng-snap#4]
@popey
The permissions is to time for audio:record OFF. See picture attached.
Please change the default from OFF to ON.
Thank you very much for your work.

![permissions](https://user-images.githubusercontent.com/3152567/85941466-871c6380-b923-11ea-98ba-40cb61780a66.png)

**Comment by popey** [comment]
This should now be resolved as per https://forum.snapcraft.io/t/audio-record-for-vokoscreen-ng/18443
